[package]
name = "portaldi-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Macros for portaldi."

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.39", features = [
    "full",
    "extra-traits",
    "visit-mut",
    "visit",
] }
darling = "0.20.3"
regex = "1.7.0"
once_cell = "1.16"

portaldi-core.workspace = true

[lib]
proc-macro = true
