[package]
name = "portaldi-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Macros for portaldi."

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = {version = "1.0.86", features = ["full", "extra-traits", "visit-mut", "visit"]}
darling = "0.14.2"
regex = "1.7.0"
once_cell = "1.16"

portaldi-core.workspace = true

[lib]
proc-macro = true

