[package]
name = "portaldi-root"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
portaldi = { path = "packages/index" }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[workspace]
members = [
    "packages/index",
    "packages/core",
    "packages/macros",
]
