[workspace]
members = ["packages/index", "packages/core", "packages/macros"]

[workspace.package]
version = "0.1.5"
edition = "2021"
authors = ["mtn81 <nantsuka2011@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mtn81/portaldi"

[workspace.dependencies]
portaldi-core = { path = "packages/core", version = "0.1.5" }
portaldi-macros = { path = "packages/macros", version = "0.1.5" }
