[package]
name = "portaldi"
version = "0.1.0"
edition = "2021"
authors = ["mtn81 <nantsuka2011@gmail.com>"]
description = "An ergonomic lightweight compile time depencency injection libray."
license = "MIT OR Apache-2.0"
repository = "https://github.com/mtn81/portaldi"
readme = "../README.md"
keywords = ["di", "ioc", "dependency", "inversion", "dependency-injection"]

[dependencies]
portaldi-macros = { path = "../macros", version = "0.1.0" }
portaldi-core = { path = "../core", version = "0.1.0" }

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
