[package]
name = "portaldi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "An ergonomic lightweight compile-time depencency injection library."
readme = "../../README.md"
keywords = ["di", "ioc", "dependency", "inversion", "dependency-injection"]

[dependencies]
portaldi-macros.workspace = true
portaldi-core.workspace = true

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[features]
default = []
futures-join = ["portaldi-macros/futures-join"]
wasm = ["portaldi-core/wasm", "portaldi-macros/wasm"]
