cargo-features = ["per-package-target"]

[package]
name = "portaldi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core functionalities for portaldi."
# forced-target = "wasm32-unknown-unknown"

[dependencies]
once_cell = "1.16"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = []
