[package]
name = "portaldi-macros-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
portaldi = { path = "../index" }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

