name: Release

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.PERSONAL_ACCESS_TOKEN}}

    - name: Update version for release
      run: |
        version='0.2.6'
        echo "Debug: release version is $version"
        sed -i -e "s/^version = .*#tag:release-version$/version = \"$version\" #tag:release-version/g" ./Cargo.toml
        echo "Debug: Cargo.toml"
        cat ./Cargo.toml

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated version update on release
        branch: main
